name: Deploy to EC2

on:
  push:
    branches:
      - main  # or master, depending on your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop myapp || true
            docker rm myapp || true
            docker pull rebik/myapp
            docker run -d -p 80:3000 --name myapp rebik/myapp

